#!/bin/sh
echo Hello
pkg install git -y
if [ -z $(which bay) ]; then
git clone https://github.com/Questandachievement7Developer/UnifiedContainer 
cd UnifiedContainer
chmod +x ./unifyServer
./unifyServer install yes
echo Project bay has been installed
bash ${0}
else
echo Project Bay has been installed
bay import "https://github.com/Questandachievement7Developer/containers_EmpiresandAllies
printf "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
echo Now you can launch Empires and allies server from this command 
echo "=========="
echo "bay launchfg empiresserver"
echo "=========="
fi
