#!/bin/sh
echo Hello Welcome to the empiresandallies complex server
pkg install git busybox -y
which(){
busybox which
}
if [ -z $(which bay) ]; then
git clone https://github.com/Questandachievement7Developer/UnifiedContainer 
cd UnifiedContainer
chmod +x ./unifyServer
./unifyServer install yes
echo Project bay has been installed
#bash ${0}
fi
echo Project Bay has been installed
env SCRIPTCALL=1 bay remove empiresserver
sleep 5
bay import "https://github.com/Questandachievement7Developer/containers_EmpiresandAllies"
#bay update empiresserver
bin="${PREFIX}/bin/empires-server"
echo "#!/bin/bash" > ${bin}
echo "bay launchfg empiresserver" >> ${bin}
chmod +x ${bin}

printf "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
echo Now you can launch Empires and allies server from this command 
echo "=========="
echo "empires-server"
echo "=========="
echo "++++++++++"
echo " IF YOU HAVE any problem with the empiresserver Please do "
echo "bay update empiresserver"
echo "or if you want a total fix by nuking the container"
echo "bay reset empiresserver"
echo "++++++++++"
echo "This server is powered by python and unifiedContainer Technology"
